version: '3'
services:
  ingress:
    container_name: openresty
    build:
      context: .
      dockerfile: ./build/Dockerfile.resty
    ports:
      - "80:80"
    volumes:
      - ./lua/plugins:/etc/nginx/lua/plugins
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./config.example.json:/etc/nginx/config.example.json
      - ./t:/etc/nginx/t
      - ./bin/busted:/bin/busted
    environment:
      - MTAG_CONTROLLER_HOST=controller:81
      - MTAG_CONTROLLER_SSL=false

  controller:
    container_name: controller
    build:
      context: ./examples/controller
      dockerfile: Dockerfile
    ports:
      - "81:81"
    volumes:
      - ./examples/controller:/app
